apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        tier: back-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
