apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: NodePort
  ports:
    - port: 80 # on the actual service
      targetPort: 80 # on the pod
      nodePort: 30008 # on the node (30_000 .. 32_767)
  selector:
    app: myapp
    tier: back-end
