apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: ClusterIP
  ports:
    - port: 80 # on the actual service
      targetPort: 5000 # on the pod (e.g. flask backend)
  selector:
    app: myapp
    tier: back-end
